### ISSUE TITLE
npm test doesn't run

### ISSUE THREAD

**Issue by timothyylim** [alexandercerutti/node-telegram-operation-manager#1]
Hi thanks for making this package 😄 

However, I'm having trouble getting it to work. 

I've cloned the repo and tried the following:

```
npm install -D
npm test
```

but I'm getting the following error:

![skjermbilde 2018-12-21 kl 09 47 57](https://user-images.githubusercontent.com/6047346/50333516-ebc45a00-0505-11e9-89a7-8bd396feb5d9.png)

**Comment by alexandercerutti** [comment]
Hi! `tsc` is the typescript compiler. I installed it globally and forgot to put it in dependencies.
Try to install it globally through `sudo npm install -g typescript`.

This is required as each "pre" operation is set to compile the whole project before running the operation itself.

**Comment by timothyylim** [comment]
Thanks, I've installed typescript globally but am still getting this:

![skjermbilde 2018-12-21 kl 10 06 09](https://user-images.githubusercontent.com/6047346/50334302-216a4280-0508-11e9-8eb6-f3248081a1aa.png)

**Comment by alexandercerutti** [comment]
Okay, I tried to clone and run tests a discovered a thing: first, I forgot to commit the `tsconfig.json` which does not let me compile (I used .gitignore also for npm, which this is not good in this situation).
Two: there might be a problem with tests path in configuration.

Today I probably won't have enough time to commit them. I'll do it asap. Thank you for the report!

**Comment by timothyylim** [comment]
Thanks so much 👍 I'm just trying to get the examples to work :)

**Comment by alexandercerutti** [comment]
If you have any doubts or issues with the examples, please open another issue. 😉
I'll update you in this topic as I have news.

**Comment by alexandercerutti** [comment]
@timothyylim my flight delayed, so I had a bit of time to put my hands on this.
I pushed the `tsconfig.json` and tested and it seems to work.
Can you please try to pull the latest changes and try again? I also added typescript to dev dependencies

**Comment by alexandercerutti** [comment]
@timothyylim were you able to execute the tests successfully with the new commits?

**Comment by timothyylim** [comment]
@alexandercerutti sorry, am in the countryside. Will test soon and get back to you :)

**Comment by timothyylim** [comment]
Nice work :)) thanks!
