### ISSUE TITLE
Suggestion on returning false

### ISSUE THREAD

**Issue by inyutin** [alexandercerutti/node-telegram-operation-manager#2]
I ran into a problem that I want to repeat action, but pass some additional data.
In first case I need to return false, in second one - object with data. 
Actually it quite strange that sometimes we return bool, sometimes object.
Maybe it will be better if for repeat we return something like {repeat: true}?
In this case we can pass additional info too.
What do you think?

**Comment by alexandercerutti** [comment]
Hi! Yeah, it is weird in terms of "architecture", if we can say so. I agree with you.
I'll try shortly to apply this thing. 😊
What about "success" instead of repeat?

**Comment by inyutin** [comment]
As you wish :)
I can do a PR if you don't mind

**Comment by alexandercerutti** [comment]
Thank you very much, but while applying the changes, I discovered more things to correct! 😊 I also have to update the documentation since I forgot to mention the fact you can pass the previous datas

**Comment by alexandercerutti** [comment]
Anyway, @inyutin, you are making me thinking: should the lib let anyone to repeat a reply multiple times for some reasons outside the of failure? If so, a "repeat" may have sense... 🤔🤔

**Comment by inyutin** [comment]
Yes, of course.
Let me describe what I try to build.
I ask user to send me photo. So, when he send me text, I want to answer him with special text and want repeat waiting new message. 
What's more I want to delete previous message and send new one, cause it looks pretty. For this purpose I need pass previous message id.

So I can repeat multiple times and every time need to pass data.

**Comment by alexandercerutti** [comment]
Got it. Okay, so is it better to have only one flag, for you, or two (success and repeat)?
Maybe only repeat...

**Comment by inyutin** [comment]
Only one - repeat, but it need to be passed every time
We return {repeat: true} or {repeat:false}

**Comment by alexandercerutti** [comment]
What about true or optional? I mean, if it is false or the dev does not include it, we can assume the lib doesn't have to repeat it.

**Comment by inyutin** [comment]
Okay, we can do like this

**Comment by alexandercerutti** [comment]
I've created a new branch, [1.2.0](https://github.com/alexandercerutti/node-telegram-operation-manager/tree/1.2.0) with inside the new code.
Can I kindly ask you to download it, place in your `node_modules`, build it through `npm run build` and try to run with the appropriate changes (so, with "repeat") and tell me if its okay? :)
Building should automatically install typescript globally (if you don't have it yet)
If you confirm this, I'll publish it on NPM.

**Comment by inyutin** [comment]
@alexandercerutti I will try it, but a bit later

**Comment by alexandercerutti** [comment]
Okay, no problem! Let me know! 👍

**Comment by inyutin** [comment]
@alexandercerutti 
Hello! Sorry for late answer. I try it and it's okay, thank you

**Comment by alexandercerutti** [comment]
Okay, today I'm going to publish it and tell you once done. Be sure to update. 😊 Thanks to you

**Comment by alexandercerutti** [comment]
@inyutin done! I've published v1.2.0 on NPM and merged the branch with master! 😃 Thank you for the help to improve this!

=========

What about leaving a star 🌟 on the project? 😊
