### ISSUE TITLE
Perform async operations inside a registered action

### ISSUE THREAD

**Issue by jfet97** [alexandercerutti/node-telegram-operation-manager#3]
I need to perform an asyncronous operation inside an action, but currently seems not possible, because an action has to return an object and cannot return a Promise. 
Of course a Promise could be returned, but the logic to handle it is not present.

So, what if the resolution of the `repeat` flag is connected with that async op? Or what if the result of an action is derived from one or more async ops?

**Comment by alexandercerutti** [comment]
Can you please show me a better example of what do you mean? Thank you.

**Comment by jfet97** [comment]
Sure @alexandercerutti . I'll try with a simple example.
Let's say we need a bot that asks to the user some info, next it will fetch some data thanks to those info and then it will ask to the user in which format he wants the result. After the user has chosen one format (json, csv, xml) the bot does another request to a service that will convert data into the selected format. Finally the bot will send the file to the user.

So there are two async operations: 
1) the bot will fetch an API to get some data thanks to the info inserted by an user
2) the bot will ask to the remote service the creation of a file

This is how we should be able to write the flow (skipping the unuseful parts):
```js
bot.sendMessage(msg.from.id, "tell me what you want to look for");

reply.register(msg.from.id, async data => {
        const {
            msg
        } = data;

        try {
            let result = await fetch("http://searchapi.com/search?field=" + msg.text);
            bot.sendMessage(msg.from.id, "chose a format for the data: csv or json or xml");
            return {
                result
            };
        } catch (e) {
            bot.sendMessage(msg.from.id, "an error occured, try again");
            return {
                repeat: true
            };
        }
    })

    .register(msg.from.id, async data => {
        const {
            msg
        } = data;

        if (!["csv", "json", "xml"].includes(msg.text.toLowerCase())) {
            bot.sendMessage(msg.from.id, "invalid format, try again");
            return {
                repeat: true
            };
        }

        try {
            let result = await fetch(`https://converter.com/conv?format=${msg.text}`, {
                method: 'post',
                body: JSON.stringify(data.previousData.result)
            });
            bot.sendMessage(msg.from.id, "Here it is: ");
            bot.sendFile(result.url);
            return;
        } catch (e) {
            bot.sendMessage(msg.from.id, "an error occured, try again");
            return {
                repeat: true
            };
        }
    });
```

As you can see, the *actions* are **async functions**, so them will return Promises. And the way they are used is sufficient to cover all the requirements of the previous post.

What does it mean, from the library perspective? 

At the moment, if you register e.g. three actions, if two messages come in row from an user the flow is the following:
1. "message" listener is called
2. `reply.execute()` is called
3. first registered action is performed (take the case where everything runs smoothly)
4. the action code ends
5. `reply.execute()` code ends
6. "message" listener code ends, but there is already another message
7. "message" listener is called
8. `reply.execute()` is called
9. second  registered action is performed (take the case where everything runs smoothly)
10. the action code ends
11. `reply.execute()` code ends
12. message" listener code ends and there are no further messages, so we are waiting the third

This is perfect for sync tasks because each `reply.execute()` call is immediately followed by the corrispettive action call. 
But in the async realm it happens that if the action is async, its execution could be stopped...and if two messages come in row the message listener could be called more repeatedly, so there would be another `reply.execute()` call when the first action is not yet terminated.
Here's what would happen:
1. "message" listener is called
2. `reply.execute()` is called
3. first registered action is performed and there is an async operation
4. first registered action is stopped
5.  "message" listener is called again because there is already another message
6. `reply.execute()` is called again wrongly, because the first call is not yet ended, the first action is not yet ended
7. second registered action is wrongly performed, DISASTER!!!
8. (at a some points in the future) first registered actions ends but we are in trouble

So some changes should be made in the library to correctly handle async operations with promises. Each call to `reply.execute()` should be intercepted and queued, in order to be able to syncronize each action's end and its result (that might be a promise so should be awaited) with the next call to  `reply.execute()`.

**Comment by alexandercerutti** [comment]
So, let me recap to see if I understood what you mean.
The flow you showed me, is async. Therefore if the user sends a message while another is being "processed" (async ops.), the flow will anyway continue without waiting for the end of the previous one.

Well, one solution might be to set all the async operations to `await` IMHO. But I've not tested it. You are right, this is good for "synchronous" flow (which is not really synchronous, but sort of). In fact, I've created this library, based on my needs when I created my own bot (which is not maintained anymore). This is in fact, like a fork.

Anyway, for what I'm understanding, the changes you are proposing (which still are not that clear to me), would mean to introduce a breaking change. Let's discuss how to improve this. 😊

**Comment by jfet97** [comment]
@alexandercerutti
You've understood perfectly the main problem, but the solution you proposed it's not exactly what we need. I'll try to explain better, broadly, what I had in mind.

Let's say there are two async registered actions, **a1** and **a2**, because a specific _bot_command_ was used. Let's assume that the user sends the two needed messages in row, **m1** and **m2**. The first starts the execution of **a1** that is async, so as you have understood **m2** is handled by the _message listener_ earlier than expected, wrongly triggering the execution of **a2**. Where is the problem? We cannot avoid the premature calls to the _message listener_, but we could better handle the calls to `reply.execute()` that are contained in that listener. To synchronize everything, the calls to `reply.execute()`, **rec1** and **rec2**, should be queued. 

The succession of events should be more or less the following:
1.  **a1** and **a2** were registered
2. two incoming messages, **m1** and **m2**
3. first call to the _message listener_
4. **rec1**, the first call to `reply.execute()`, is queued
5. currently there are two registered actions and one registered call to `reply.execute()`: **a1** can be triggered wit **m1**, the first message
6. **a1**  is async, so it's paused. The second incoming message is handled
7. second call to the _message listener_
8. **rec2**, the second call to `reply.execute()`, is queued
9. currently there are two registered actions and two registered call to `reply.execute()`: **a1** is in asynchronous execution so **a2** won't be triggered. Two things can happen:
10. **CASE 1, SUCCESS**: **a1** ends successfully producing a result, **r1**. We can remove from the queues  **a1** and **rec1**. Currently there is a registered action, **a2**, a registered `reply.execute()` call, **rec2**, a registered result for **a2**, **r1** (it will become `previousData`) and a registered message, **m2**. The execution of **a2** should be started. 
**CASE 2, FAIL**: **a1** fails so a Promise containing `{repeat:true}` is returned. As you know, **a1** should be repeated with the next message, message that is already present, it's **m2**. Let's make things easier, **m2** was correct and **a1** ends successfully with a result, **r1**. Finally we can remove from the queues **a1** and **rec1**. Currently there is a registered action, **a2**, a registered `reply.execute()` call, **rec2**, a registered result for **a2**, **r1** (it will become `previousData`). Just a message is missing, **m3**, because **m2** was used for **a1**. When **m3** will come, the execution of **a2** should be started.

Final considerations:
* there should be no breaking changes in the API of the library, because the **sync** case is only an **async** that immediately ends. In other words, `await cb();` is prefectly acceptable both that the `cb` (the action) is sync or async. The internal behaviour of the library should be redefined, of course, but externally should not change anything.
* I'm not the best in reading and understanding other people's code. And I'm a fool with TypeScript. There are a number of points in the library that are obscure to me. I'm one of those people who prefer rewrite other people's code instead of understand it 😂😂😂. Therefore, if the cost of the change I am submitting to you is too high, we could definitively consider a breaking change. I could try to calmly rewrite the library on my own with some simplification in mind, e.g. no operation manager, only one forced action list where you cannot never register other actions if an op is being performed, an easier way to integrate the library with the _message listener_ and other listeners.
When I will arrive at a decent point, including the management of an async flow, we could discuss it again, evaluate its status and quality and if it will be good enough integrate Typescript to release it to the NTBA community.

**Comment by alexandercerutti** [comment]
Hey, sorry for the late response! I was really busy.

Yeah, okay, my solution is not definitely not correct.
I think that there are different ways to proceed with this. Many may not work as I should think about them when I'll have a better mind to think about this (like, this weekend maybe?).
- study again the whole flow of the library and think it in a different way
- Create something like an execution queue that will tell if the user is already doing an operation
- Introduce a sort of `hasActive` for Replies that could be used on the bot side to check if the user has triggered some operation and the bot is waiting to end.

About the behavior, well... I'm not just up for this right now, sorry 😅.

**Comment by jfet97** [comment]
Hi @alexandercerutti! No problem for the delay, of course.

I didn't have much to do last Sunday and Monday evening, so I've rewrited the library on my own. 
I'm quite satisfied with the result: it's a bit simpler than the current implementation because, as I said, I've forced one operation at time and, most importantly, it does support async `actions`.

I've also created a personal bot, to handle personal files, that has needed inline keyboards, async `actions` and so on. At the moment everything seems to be going well. 

So what should I do? I was wondering about releasing it for the community, but it would become nothing but a competitor of your. What do you think about that?

**Comment by alexandercerutti** [comment]
Lucky you!
Oh, well...
How is it simpler? Anyway, you are talking about the `reply` module, don't you?
What about merging the two? We should compare them and move yours to Typescript.

**Comment by jfet97** [comment]
@alexandercerutti 
It's simpler because the API was brought to the essential, less stuff to understand and learn to be productive. Furthermore the `operation` module is no more necessary, because only one operation at a time is allowed. 
So a merge it is not exactly practicable, even if the spirit is similar.

I forgot to say that, for personal exercise, I've tried to write the library in TS, so there is no need to move it. Maybe I should release it to let you, and other devs, try the whole stuff (when you have time obviously), after I have written the documentation.

**Comment by alexandercerutti** [comment]
Well, I feel a bit like as if I've just been stabbed 😂😂.
I'd like to see your code, and see it in action. Don't worry about writing complex and complete documentation. I'm really curious about it.

**Comment by jfet97** [comment]
Ahahaha @alexandercerutti  I'm a traitor 😂😂😂
I think I'll send to you in private the library, so you can copy from it 😝😝😝 
No I'm kidding. You'll find almost successful attempts to implement those few healthy principles of OOP that I know, in a language that I don't know.

**Comment by umitsamli** [comment]
I am having similar problem. For this, I added the code to my own project and updated it.
Updated Section:

ReplyManager.execute 



`


        if (result instanceof Promise || (result != null && typeof result == "object" && result.then)) {
            result.then(response => {
                 if (response === undefined) {
                    this.remove(id);
                    return;
                }
                if (typeof response === "object" && !Array.isArray(response)) {
                    if (!response.repeat) {
                        // if we have to want to repeat, we have to shift the reply
                        this.remove(id);
                    }

                    let nextReply = this.get(id);

                    // this.get returns an empty object if there
                    // is no other reply in the id's queue.
                    if (!Object.keys(nextReply).length) {
                        return;
                    }

                    delete response.repeat; // even if it does not exists
                    nextReply.previousData = response;
                }

            }).catch(error => { this.remove(id); });
        } else {
            if (typeof result === "object" && !Array.isArray(result)) {
                if (!result.repeat) {
                    // if we have to want to repeat, we have to shift the reply
                    this.remove(id);
                }

                let nextReply = this.get(id);

                // this.get returns an empty object if there
                // is no other reply in the id's queue.
                if (!Object.keys(nextReply).length) {
                    return;
                }

                delete result.repeat; // even if it does not exists
                nextReply.previousData = result;
            }
        }
`

**Comment by alexandercerutti** [comment]
Package has been deprecated.
