### ISSUE TITLE
tslint error

### ISSUE THREAD

**Issue by Aazerra** [alexandercerutti/node-telegram-operation-manager#5]
hello 
I start to use this wrapper for my bot in typescript 
but I get this error at tslint when I use callbacks

```
Argument of type '(emailData: ReplyData) => void' is not assignable to parameter of type '(data?: ReplyData) => RegisteredResult'.
  Type 'void' is not assignable to type 'RegisteredResult'.ts(2345)

```
```
operationManager.register(msg.from.id, emailData => {
            user.email = emailData.text
            user.save()
            bot.sendMessage(msg.from.id, 'input you password').catch(err => { if (err) console.log(err) })
```
i cant start my bot script for this error

**Comment by alexandercerutti** [comment]
Make your callback return like an empty object or `{ repeat: false }` 😉

**Comment by Aazerra** [comment]
sorry 
I don't understand what you say

**Comment by alexandercerutti** [comment]
This is weird: operationmanager doesn't have that signature... 🤔 I have to investigate more on this...

**Comment by alexandercerutti** [comment]
@TahaPY, you are using `operationManager` in the wrong way: it has three params, not two.

```typescript
public register(id: number | string, command: string, callback?: Function): any;
```

**Comment by Aazerra** [comment]
oh sorry i forget to say you i use replymanager and i define 
`const operationmanager = new ReplyManager()`

**Comment by alexandercerutti** [comment]
That is really clear, of course 😂You should use something like `const ReplyManager = new ReplyManager()`.

As I said before, you should make the function return an object that is compliant with `RegisteredResult` signature, which accept arbitrary keys to be passed to the next replies and one special key: `repeat`. If repeat has a truthy value, the reply won't be discarded and repeated as the next reply. If you omit it, the current reply will be used only one time.

If you don't need to pass any value to the next reply, just return an empty object:

```typescript
operationManager.register(msg.from.id, emailData => {
            user.email = emailData.text
            user.save()
            bot.sendMessage(msg.from.id, 'input you password')
                        .catch(err => {
                                    if (err) console.log(err)
                        });

            return {};
})
```
